### ISSUE TITLE
maybe should close the sourcemap in 'production' mode?

### ISSUE THREAD

**Issue by cbbfcd** [ampproject/filesize#12]
thx, i like this repo, i have an idea just as the title :
```js
// ...
process.env.NODE_ENV === 'development' && magicString.generateMap({ hires: true })
// ...
```

**Comment by kristoferbaxter** [comment]
Hi there,

MagicString is used during rollup of the executable, is there a disadvantage to generating the valid sourcemap for developers of this tool?

I'm happy to make the change, but want to understand the motivation a bit more.

**Comment by cbbfcd** [comment]
@kristoferbaxter thx reply,
Usually in the development environment, we need the sourcemap, but in the production environment, this involves some security risks, and the sourcemap is usually not exposed

**Comment by kristoferbaxter** [comment]
I understand where you're coming from now.

Since this tool is shipped for developers to use as a `devDependency` it should never realistically end up in a production bundle. Having sourcemaps available doesn't carry as much concern here.

**Comment by cbbfcd** [comment]
i got it! thx very much.
