### ISSUE TITLE
Deltas and Automatic Deployment

### ISSUE THREAD

**Issue by kristoferbaxter** [ampproject/filesize#13]
In the output include a pre-made Github Action that does the following:
1. Capture result of `filesize` for the current PR.
2. Compare size to pre-stored base (storage is on `gh-pages`).
3. Report delta as a PR comment.
4. Publish PR artifacts and size to `gh-pages`.

**Comment by developit** [comment]
I scratched out a rough implementation to start from, based on where this would fit into the current code for `compressed-size-action`:

```js
const uploadBranch = getInput('upload-branch');  // target branch
const uploadDir = getInput('upload-dir') || 'assets'; // target dir
const uploadPattern = getInput('upload-pattern') || '**'; // files to upload
const uploadBase = getInput('upload-base'); // eg: "./dist"

// exiting logic to build current commit
/* snip */

// before continuing, store the built files and current tag for later use.
// we'll need these if we're uploading them at the end.
let currentTag, files, data;
if (uploadBranch) {
  currentTag = await exec(`git tag --points-at ${sha}`);
  // store files in-memory before changing branches.
  // note: actions-toolkit's glob() doesn't have a cwd option.
  if (uploadBase) process.chdir(uploadBase);
  files = await (await glob.create(uploadPattern)).glob();
  data = await Promise.all(files.map(f=>fs.readFile(f, 'utf-8')));
  if (uploadBase) process.chdir(cwd);
}

let sizesBefore;
// If we're configured to upload assets, each upload has a JSON copy of the sizes.
// Try to grab that copy for the base branch instead of checking out and building it.
if (uploadBranch) {
  try {
    await exec(`git checkout ${uploadBranch}`);
    const base = pr.base.sha;
    const stats = path.resolve(__dirname, uploadDir, base, 'stats.json');
    sizes = JSON.parse(await fs.readFile(stats, 'utf-8'));
  } catch (e) {}
}
if (!sizesBefore) {
  // We didn't have cached stats. Fall back to exiting logic to build $base commit
  await exec(`git checkout ${base}`);
  await exec(`${npm} run build`);
  // etc..
}

// Existing logic to post/update the size comment
/* snip */

// now let's upload the build result.
if (uploadBranch) {
  await exec(`git checkout ${uploadBranch}`);
  const target = path.resolve(__dirname, uploadDir, sha);

  // store stats for this commit hash
  const stats = path.resolve(target, 'stats.json');
  await fs.writeFile(stats, JSON.stringify(sizes));

  // copy files
  await Promise.all(files.map((file, i) => {
    fs.writeFile(path.resolve(target, file), data[i]);
  }));

  // add a symlink if we built a tag
  if (currentTag) {
    const tag = path.resolve(target, '..', currentTag);
    await exec(`ln -s ${JSON.stringify(target)} ${JSON.stringify(currentTag)}`);
  }

  // upload it
  await exec(`git add -A ${uploadDir}`);
  await exec(`git commit -m '[assets] ${sha} ${currentTag || ''}'`);
  await exec(`git push`);
}

// and we're done!
```

**Comment by kristoferbaxter** [comment]
@rsimha Can you and team comment on incorporating the remainder pieces of `bundle-size` tracking and enforcement to the `filesize` project instead of siloed within `amphtml`?

**Comment by rsimha** [comment]
Sure thing. First, some history:

- The `bundle-size` task in `amphtml` was written a couple years before `filesize` was created. At the time, it contained code to extract the sizes of binaries in a given directory, and to report results to a github status check.
- As the capabilities of `filesize` grew, all the size extraction code in `bundle-size` code was replaced by a [single call to `filesize`](https://github.com/ampproject/amphtml/blob/92abb24cd5d2b7741aae7097fc2e2a8f43cf1a96/build-system/tasks/bundle-size/index.js#L60-L65). The task's output now [comes directly from](https://github.com/ampproject/amphtml/pull/32479#issue-568685809) `filesize`.
- Today, all that's left in the `amphtml` repo is wrapper code to report the data extracted by `filesize`. The business logic of updating the github status is already part of a standalone app that lives in the [`amp-github-apps` repo](https://github.com/ampproject/amp-github-apps/tree/master/bundle-size).
- The app provides [an API](https://github.com/ampproject/amp-github-apps/tree/master/bundle-size#webhooks-and-api) that can be [configured](https://github.com/ampproject/amp-github-apps/blob/master/bundle-size/redacted.env) and used by any repo.

Re: the specific request:

- Given that the `bundle-size` task only contains wrapper code, I don't believe there's much else that can be moved out of `amphtml`.
- If other repos would like to use the tracking and enforcement functionality, it should be possible to install an instance of [the app](https://github.com/ampproject/amp-github-apps/tree/master/bundle-size) and use [the API](https://github.com/ampproject/amp-github-apps/tree/master/bundle-size#webhooks-and-api).
- If there are specific things in the app implementation that are currently hard-coded to only work with `amphtml`, I'm supportive of changing them into configurable settings via [this environment file](https://github.com/ampproject/amp-github-apps/blob/master/bundle-size/redacted.env).
- However, I don't think it makes sense to move the entire app implementation from `amp-github-apps` to `filesize`.

/cc @ampproject/wg-infra to keep me honest here, and add anything I might have missed.

**Comment by danielrozenberg** [comment]
There are quite a few things in the app that are hard coded for amphtml, but it shouldn't be a big deal to modify those to become environment variables

The main thing in the `amp bundle-size` task that can't be generalized is that, because of the way Brotli compression works, we have to normalize the AMP version inside the compiled files to get a fair comparison. Other than that it's smooth sailing

**Comment by kristoferbaxter** [comment]
Closing this issue since @ampproject/wg-infra is not interested in making the changes.
