### ISSUE TITLE
Add support for a standalone config file

### ISSUE THREAD

**Issue by rsimha** [ampproject/filesize#83]
Today, `filesize` can only read its config from the project root `package.json`. Per https://github.com/ampproject/amphtml/pull/26907#discussion_r383399093, we'd like to move the config to a local standalone file like `.filesizerc.json`, similar to [`.renovaterc.json`](https://docs.renovatebot.com/configuration-options/).

I'm filing this issue because the `filesize` config in `package.json` currently [breaks compatibility](https://travis-ci.org/github/ampproject/amphtml/jobs/678816324#L406-L411) between `yarn add` and `prettier`, causing them to go back and forth on formatting.

**Comment by kristoferbaxter** [comment]
Happy to make this change, shouldn't take long.

**Comment by kristoferbaxter** [comment]
Resolved with https://github.com/ampproject/filesize/pull/87 and released in https://github.com/ampproject/filesize/releases/tag/v4.2.0.
